# Generated by Django 2.2 on 2020-02-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_colour', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredefinedColours',
            new_name='PredefinedColour',
        ),
    ]
